### ISSUE TITLE
Force login redirect error

### ISSUE THREAD

**Issue by lukestanley** [blip-solutions/promptwatch-client#11]
Hi I wanted to this but ran into an error right away:
Steps to reproduce:
1. Visit homepage
2. Request login free key
3. Look at link to explore prompt requests made
4. Got unexpectedly redirected to https://www.promptwatch.io/login?force=true

**Comment by ju-bezdek** [comment]
Thanks... I was able to reproduce it...
I will investigate it... in the meantime you can sign up, that should work just fine

**Comment by ju-bezdek** [comment]
Ok, fixed now... the temp api key kept getting removed from URL params when syncing with UI filters. Should be fine now
