### ISSUE TITLE
Various errors

### ISSUE THREAD

**Issue by bmanturner** [blip-solutions/promptwatch-client#13]
When I run my unit tests I always have to wade through error messages from promptwatch. This is on latest langchain (198), but I've noticed it for the past ~20 version or so. Do these automatically get logged for you to debug?

```bash
Error in on_chain_start callback: argument of type 'NoneType' is not iterable
Error in on_chain_start callback: argument of type 'NoneType' is not iterable
Error in on_chain_start callback: argument of type 'NoneType' is not iterable
Error in on_llm_start callback: ParallelPrompt.__init__() got an unexpected keyword argument 'prompts'
Error in on_llm_end callback: 'NoneType' object has no attribute 'thoughts'
Error in on_chain_end callback: 'NoneType' object has no attribute 'outputs'
Error in on_chain_start callback: argument of type 'NoneType' is not iterable
Error in on_chain_start callback: argument of type 'NoneType' is not iterable
Error in on_chain_end callback: 'NoneType' object has no attribute 'outputs'
Error in on_chain_end callback: 'NoneType' object has no attribute 'outputs'
Error in on_chain_end callback: 'NoneType' object has no attribute 'outputs'
Error in on_chain_end callback: 'NoneType' object has no attribute 'outputs'
```

**Comment by ju-bezdek** [comment]
This is not supposed to happen... this is happening during unit tests?
No, these errors are not being sent to the server, so thanks for raising this.

What version of promptwatch client are you running? 

They were several updates and fixes tackling the part of the code where you are experiencing this, but I'm not aware of anything that should by varying by recent langchain versions. 

I can see from the logs that this is not the latest version, but I'm not sure if the latest will fix all of this.

I also assume from the logs, that you are invoking multiple prompts in a single call... this approach wasn't heavily tested. If you could share a bit from your chain that is using this (don't need the prompt nor data, just the general architecture/structure of that chain) it would be helpful.

**Comment by bmanturner** [comment]
I'm on what I believe to be the latest (`promptwatch==0.2.2`). I will return with the requested info when I have a moment. Might be tomorrow.

**Comment by ju-bezdek** [comment]
Yeah, OK I think I can see what is going on, but I don't know why... 
the only explanation that I have for now is that you are calling llm directly, not wrapped in LlmChain... that might explain a lot.

I will try to reconstruct the situation based on my assumptions, but more info will be helpful once you'll have a moment.

**Comment by ju-bezdek** [comment]
Yo!
I believe I've found the issue(s) and fixed them. pls upgrade to v0.2.3

Let me know if it helped

> PS: the support for parallel request via `llm.generate([list of prompts])` (which is what I believe you've been using) method is limited for now... (meaning that you wont get everything working) ... but using async with regular LLMChain should work fine...

**Comment by bmanturner** [comment]
That didn't seem to do it. 

What is your email? I'd like to send you the chains (2) I'm using and prefer not to share them here. 
Feel free to reach out at brendan.turner@heavy.ai

**Comment by ju-bezdek** [comment]
pls try:
pip install -i https://test.pypi.org/simple/ promptwatch==0.2.4rc1

**Comment by bmanturner** [comment]
Ran all my unit tests and received no errors. Awesome! Thanks!

**Comment by ju-bezdek** [comment]
awesome... will release official fix soon

**Comment by ju-bezdek** [comment]
v0.2.4 released
