### ISSUE TITLE
Problems wrapping an AgentExecutor

### ISSUE THREAD

**Issue by pacepace** [blip-solutions/promptwatch-client#18]
Hello.  First, thank you for PromptWatch!

I'm having an issue where I'm attempting to use PromptWatch with an AgentExecutor and I get this error:

AttributeError: module 'langchain.callbacks.manager' has no attribute '_configure'

Some code:
```
# llm setup
llm_with_stop = self.llm.bind(stop=["\nObservation"])

# agent setup
self.prompt = register_prompt_template('agentconversationprompt', self.prompt)
agent = {
	"input": lambda x: x["input"],
	"agent_scratchpad": lambda x: format_log_to_str(x['intermediate_steps']),
	"chat_history": lambda x: x["chat_history"]
} | self.prompt | llm_with_stop | ReActSingleInputOutputParser()

# agent executor
agent_executor = AgentExecutor(agent=agent, tools=self.tools, verbose=True, memory=conversation,
							handle_parsing_errors=True, max_iterations=config.AGENT_MAX_ITERATIONS,
							max_execution_time=config.AGENT_MAX_EXECUTION_TIME, timeout=config.AGENT_MAX_EXECUTION_TIME)

# execute with PromptWatch
with PromptWatch(api_key=config.PROMPTWATCH_API_KEY):
	output = agent_executor.invoke(input)['output']

return output
```

Any suggestions?

**Comment by ju-bezdek** [comment]
Hey there.. .this should happen if you've upgraded langchain but have still older version of PromptWatch...
are you running the latest promptwatch-client?

**Comment by pacepace** [comment]
Hey ju-bezdek.  I'm running promptwatch-0.4.0 installed via "pipenv install promptwatch".

**Comment by ju-bezdek** [comment]
Interesting... and what version of langchain are you at?

**Comment by pacepace** [comment]
langchain 0.0.340

**Comment by ju-bezdek** [comment]
Oh my, sorry, this is embarrassing... somehow the fix didnt got into the version although it was the solele reason for the release... 
please upgrade to 0.4.1 fix

**Comment by pacepace** [comment]
Thank you! Getting better -- that addressed the error message I was seeing, but now when I run my agent executor I see this:

Starting PromptWatch session: {UUID}

But I do not see this session UUID appear (or anything else) in my PromptWatch dashboard and if I search for the {UUID} I don't see it.

Some code:

```
prompt = register_prompt_template('votebot_agentconversationprompt', self.prompt)
agent = {
	"input": lambda x: x["input"],
	"agent_scratchpad": lambda x: format_log_to_str(x['intermediate_steps']),
	"chat_history": lambda x: x["chat_history"]
} | prompt | llm_with_stop | ReActSingleInputOutputParser()
agent_executor = AgentExecutor(agent=agent, tools=self.tools, verbose=True, memory=conversation,
								handle_parsing_errors=True, max_iterations=config.AGENT_MAX_ITERATIONS,
								max_execution_time=config.AGENT_MAX_EXECUTION_TIME,
								timeout=config.AGENT_MAX_EXECUTION_TIME)
with PromptWatch(api_key=config.PROMPTWATCH_API_KEY):
	output = agent_executor.invoke(input)['output']
```

**Comment by ju-bezdek** [comment]
this should be the session_id
<img width="330" alt="image" src="https://github.com/blip-solutions/promptwatch-client/assets/27913091/ff829c19-a8cb-4f4e-9ff9-0a7f94ae0229">

or you meant something else?

**Comment by pacepace** [comment]
I was able to get the session id from the log message from PromptWatch ("Starting PromptWatch session: ..."), but when I go to the portal, I see no sessions and if I search by the session Id, it doesn't find anything

**Comment by pacepace** [comment]
Is there any additional information I can provide to help troubleshoot why my sessions are not making it to my PromptWatch account/portal?

**Comment by ju-bezdek** [comment]
oh sorry i've misunderstood ...

assuming that your login email is `pace@****.org` i can see that there are indeed no logged sessions for your account

I guess there are no promptwatch warnings in console (promptwatch aways handles its exceptions, so that it would cause in production if something would go wrong) ...

Please can you share date and time (ideally at least 15min window) when you've run your session? So i can look into logs, whether the messages hasn't been rejected or something (i dont see any errors in last 7 days)

Plase note that the session is only created in promptwatch if something has been logged (some chain has been executed)

**Comment by pacepace** [comment]
That is my email.  I just ran a test.  Here's the beginning of the UUID: c656897a


pace

**Comment by pacepace** [comment]
Seems to be working now.  Thank you!
