### ISSUE TITLE
Error when executing example intergration code in Jupyter notebook

### ISSUE THREAD

**Issue by joel-lignier** [blip-solutions/promptwatch-client#6]
Hello, I'm receiving the following error when running the example code:

AttributeError: 'PromptWatch' object has no attribute '_cached_init_'

I'm new to this so any advice to help resolve this is appreciated.

**Comment by ju-bezdek** [comment]
Mm, I have a suspicion that you have the bad luck downloading a version of PromptWatch with this bug, that was available only for a few hours😅. Sorry for that.

Can you please share the version you're on (`pip show promptwatch`) it should be `0.1.1`
If it's not, please update with `pip install promptwatch -U` (if you are using pipenv then `pip uninstall promptwatch` and then `pip install promptwatch` )

If this won't help, can you please share the snippet of the example code you're using?

**Comment by joel-lignier** [comment]
Fixed it! I upgraded promptwatch and tiktoken and it is working now. 

Great tool BTW!
